Inspecting in vr
NexusSocial/nexus-vr pull request #78
Opened 2024-01-05 08:42 UTC by Schmarni-Dev

2024-01-09 04:21 UTC, TheButlah commented
Apologies, I was supposed to review this today but its gonna have to wait till tomorrow.

I do see a *lot* of old comments in the code, please try to clean those up if possible

2024-01-09 23:20 UTC, TheButlah requested changes

2024-01-09 23:20 UTC, TheButlah commented on apps/social/client/src/in_world_inspector.rs
> +fn handle_toggle(
I would rename to `toggle_inspector`, its a bit nicer.

2024-01-09 23:20 UTC, TheButlah commented on apps/social/client/src/in_world_inspector.rs
> +		.get_action_bool(ACTION_SET, "toggle")
I'm on the fence here. On the one hand, if we directly access xr controllers in the worldspace plugin, we make our lives harder in the future when networked UI comes into the picture. We then have a conflitct where some UIs are controlled via the networking sync, and some UIs are controlled by the controllers directly. If we instead just expect that *some other plugin* might control the UI transforms, and have that happen in a "PlayerInputsPlugin", that might make more sense. That plugin would be solely responsible for handling player input and provides a centralized plugin that will abstract over the various input modalities (xr, desktop, webxr). Likewise the networking plugin will synchronize the networked transforms and events.
We can then simply query for either events for visibility or changes for visibility. Likewise adjusting the pose of the window is as simple as letting bevy do it for us.

Alternatively, maybe we do want every plugin to be responsible for its own data sync and driving its own data. In that case, there would be no PlayerInputsPlugin, and this plugin would also read from the networked data model and update its own transforms. Maybe, this is the better way to do it as it provides better control over what happens, at the cost of coupling everything to the networking and input apis.

What is your opinion @Schmarni-Dev @MalekiRe?

2024-01-09 23:20 UTC, TheButlah commented on apps/social/client/src/in_world_inspector.rs
> +		.unwrap()
use expect, please replace the other unwraps too.

2024-01-09 23:20 UTC, TheButlah commented on apps/social/common/src/dev_tools.rs
> +pub struct InspectorUiTarget;
Add comment. Target of what? Also, does this need to be public?

2024-01-09 23:20 UTC, TheButlah commented on apps/social/client/src/in_world_inspector.rs
> +use std::f32::consts::{PI, TAU};
Every plugin file should have a module level comment explaining "this is what this file does!" so that people onboarding to the codebase can more easily find their way around.

2024-01-09 23:20 UTC, TheButlah commented on apps/social/client/src/in_world_inspector.rs
> +pub struct InWorldInspectorTexture(Handle<Image>);
Curious, what is the difference between this type and the `EguiRenderToTexture` type from the fork of bevy_egui?

2024-01-09 23:20 UTC, TheButlah commented on apps/social/client/src/in_world_inspector.rs
> +		app.add_systems(Startup, new_inspector_texture);
register your types so that the inspector reflect mechanism will see them

2024-01-09 23:20 UTC, TheButlah commented on apps/social/common/src/dev_tools.rs
> +impl Plugin for InspectorUiPlugin {
Every plugin should be in its own file with a module-level brief explanation.

2024-01-09 23:29 UTC, Schmarni-Dev commented on apps/social/client/src/in_world_inspector.rs
> +		.get_action_bool(ACTION_SET, "toggle")
i think each plugin should at least handle the input stuff itself so we can better take advantage of an action system (which i would like to use even outside of openxr / xr in general). for networking i would prefer to provide an easy api to handle it in the plugin too

2024-01-09 23:31 UTC, Schmarni-Dev commented on apps/social/client/src/in_world_inspector.rs
> +pub struct InWorldInspectorTexture(Handle<Image>);
it's a resource so i don't have to create a new texture every time a new inspector is opened

2024-01-09 23:40 UTC, TheButlah commented on apps/social/client/src/in_world_inspector.rs
> +		.get_action_bool(ACTION_SET, "toggle")
Ok, sounds good for now.

Long term however, I think it makes more sense to mark certain entities as "grabbable" and let a different plugin manage that transform logic on *all grabbable entities* instead of doing it ad-hoc like we do in this PR

2024-01-09 23:42 UTC, TheButlah commented on apps/social/client/src/in_world_inspector.rs
> +pub struct InWorldInspectorTexture(Handle<Image>);
What happens when we have multiple in world UIs tho?

2024-01-10 01:26 UTC, Schmarni-Dev commented on apps/social/client/src/in_world_inspector.rs
> +pub struct InWorldInspectorTexture(Handle<Image>);
this is only for the in world inspector which there currently can only ever be one

2024-01-10 01:28 UTC, Schmarni-Dev commented on apps/social/common/src/dev_tools.rs
> +pub struct InspectorUiTarget;
Would renaming this to InspectorUiRenderTarget help? it's a component placed on all entities that should display the inspector ui

2024-01-10 03:51 UTC, TheButlah commented on apps/social/common/src/dev_tools.rs
> +pub struct InspectorUiTarget;
Perfect, that works

2024-01-11 05:37 UTC, TheButlah requested changes
small nits

2024-01-11 05:37 UTC, TheButlah commented on apps/social/client/src/in_world_inspector.rs
> +use std::f32::consts::{PI, TAU};
```suggestion
//! This module is responsible for displaying an Entity Inspector in the world, so Vr Users can
//! interact with it. this inspector is not synced over the network, and only one can exist at a
//! time.

use std::f32::consts::{PI, TAU};
```

2024-01-11 05:37 UTC, TheButlah commented on apps/social/common/src/inspector.rs
> +use bevy::prelude::*;
```suggestion
//! This module is Responsible for rendering the Entity Inspector to every [`EguiContext`] where a
//! [`InspectorUiRenderTarget`] also exists.

use bevy::prelude::*;
```

2024-01-15 04:36 UTC, TheButlah approved these changes

2024-01-15 04:36 UTC, merged