Server skeleton
NexusSocial/nexus-vr pull request #79
Opened 2024-01-05 21:42 UTC by TheButlah

2024-01-23 07:12 UTC, TheButlah commented on apps/social/replicate-server/src/instance/instance.rs
> +//! Instances are not purely client or server authoritative. Instead, they follow
This file might be a bit out of date, you can review it if you want but it might not make any sense anymore.

2024-01-23 07:13 UTC, TheButlah commented on apps/social/replicate-server/src/instance/mod.rs
> +	channels: HashMap<ChannelFormat, ChannelId>,
The concept of channels isn't really a thing in the client rn so some of this might be out of sync with the current design of the client. Feel free to review but it might just need to change. We can change it in a later PR tho.

2024-01-23 14:49 UTC, CorneliusCornbread requested changes
Just some minor naming things rn, otherwise LGTM

2024-01-23 14:49 UTC, CorneliusCornbread commented on apps/social/replicate-client/examples/example-client.rs
> +pub struct Args {
~~Why is this called `Args` if this 'runs a nexus server' wouldn't it make more sense to name it as such? Like `NexusServer` or `NexusApp` or something?~~

Ahh, I didn't see the clap macros, so these are args gotten from clap, honestly, just remove the comment above this struct. I think this struct is self explanatory and the comment is misleading

2024-01-23 14:49 UTC, CorneliusCornbread commented on apps/social/replicate-client/src/instance.rs
> +pub struct Instance {
This struct could be more explicit in its name. Something along the lines of `NexusConnection` or `NexusStream`, `Instance` is just a bit vague. Or you could call it based on the lib name, `ReplicateConnection`, etc.

2024-01-23 14:49 UTC, CorneliusCornbread commented on apps/social/replicate-client/src/manager.rs
> +pub struct Manager {
Type name is vague again, `ClientManager` would likely be much more descript

2024-01-23 14:49 UTC, CorneliusCornbread commented on apps/social/replicate-server/src/instance/mod.rs
> +#[derive(Debug, Default)]
Probably want to call this `ServerManager`

2024-01-23 14:49 UTC, CorneliusCornbread commented on apps/social/replicate-server/src/lib.rs
> +/// Runs a nexus server.
Same thing with the other Args struct's comment, comment is mildly misleading.

2024-01-24 01:15 UTC, TheButlah commented on apps/social/replicate-client/src/manager.rs
> +pub struct Manager {
Its a RPC api for the `Manager`, so calling it `ClientManager` is misleading.

2024-01-24 01:16 UTC, TheButlah commented on apps/social/replicate-server/src/instance/mod.rs
> +#[derive(Debug, Default)]
Its already in the server crate

2024-01-24 01:28 UTC, TheButlah commented on apps/social/replicate-client/src/instance.rs
> +pub struct Instance {
Its not a connection or stream though. It is a particular instance.

2024-01-24 01:31 UTC, TheButlah commented on apps/social/replicate-client/src/instance.rs
> +pub struct Instance {
I added some additional comments to explain.

2024-01-24 04:24 UTC, merged